### ISSUE TITLE
lazyView and HMR

### ISSUE THREAD

**Issue by toburger** [fable-elmish/react#22]
I've noticed that HMR doesn't work when using lazyView and the other lazy functions.

The easiest workaround is to redefine lazyView locally like following:

```fsharp
let lazyView =
    #if DEBUG
    id
    #else
    Elmish.React.lazyView
    #endif
```

but then you lose the benefits of laziness in your development code. So you have to decide what is more important to you.

Do I miss something or is there a way to use both features together?

**Comment by MangelMaxime** [comment]
Indeed, when using HMR and lazyView the change in the UI aren't triggered directly.

The problem, is the lazyView is comparing the two model states because the HMR don't change the model state then the changes aren't directly visible. However, if your lazyView is wrapping an input for example, write something in your input and you will see the changes appear because the view is re-rendered.

In elmish, by default your application is wrapped in a lazyView to make HMR work I wrapped the user application in a model containing the user model and a counter. Each time the HMR is triggered, I am incrementing this counter value [code here](https://github.com/fable-elmish/hmr/blob/master/src/hmr.fs#L40) so the lazyView detect the changes.

Not sure if we want/can provide a work around in the lazyView implementation.

**Comment by toburger** [comment]
Changing the input does indeed update the view (at least for the "path" where the arguments affect the lazy views).

I think there are two requirements here:
* HMR: have a seamless developer experience and push view updates as fast as possible to the browser when developing your view
* laziness: get the best performance out of your application

A possible development workflow could be:
* design phase: enable HMR and write the code for your views
* hardening phase: disable HMR and bring in laziness to your views

**Comment by alfonsogarciacaro** [comment]
I usually do the following with the views I want to make lazy:

```fsharp
let render dispatch (model: Model) =
    ...

open Elmish.React

let view (model: Model) dispatch =
  lazyViewWith propsEqualsByRef (render dispatch) model
```

Then in a file with utilities I have:

```fsharp
/// In development this returns always false for compatibility with HMR
let inline propsEqualsByRef (x:'a) (y:'a) =
  #if DEBUG
  false
  #else
  obj.ReferenceEquals(x, y)
  #endif
```

Which is more or less what you did. In development I don't need performance but I want views to be refreshed with HMR so for me it's not an issue. But I haven't worked in an app where I had to squeeze the maximum performance in development mode too, your case may be different.

> Note that by default Elmish use structural equality but I tend to use referential equality because it's faster and works in most cases.

**Comment by et1975** [comment]
> by default Elmish use structural equality but I tend to use referential equality 

check for referential equality is the first step in structural equality check, isn't it? In other words if models doesn't change the overhead of structural equality is negligible?

>  works in most cases
If we define "works" as "avoids unnecessary view construction, rendering and diffing" structural equality is what one should use in most cases. I'd be curious to see where/how this isn't true. Perhaps we should change the default behaviour?

**Comment by toburger** [comment]
No, I don't need performance in development mode, but is is easier to test for render updates in development mode than in production mode. But this can be a special process in the development process..

I'm a bit skeptical about the short cuttet propsEqualByRef (and also my method) and ignoring equality in DEBUG mode completely, because this can lead to strange bugs in the production code which didn't appear during development.

An alternative could be to define a "HMR" compile constant and then disable equality checks if it is defined and enable HMR in elmish.
Is it possible to define constants other than the predefined DEBUG constant in fable?

**Comment by alfonsogarciacaro** [comment]
@et1975 

>  In other words if models doesn't change the overhead of structural equality is negligible?

You're right. I was mainly worried about cases where the model contains a big collection of elements: Fable may go through all (or most, it will stop as soon as a difference is found) of them and then React will also check list elements individually. That's why I considered removing the structural equality (but in other places I do use it). However, I would probably keep it as the default in Elmish, because structural equality is part of _F# semantics_ so that's what users will expect.

@toburger 

Yes, you can use the `define` option in fable-loader ([example](https://github.com/SAFE-Stack/SAFE-BookStore/blob/c4b19c69d0aa71e8c93be59915d3ee77336e135e/src/Client/webpack.config.js#L55)). This is actually how `DEBUG` is defined right now (though the next fable-loader version will try to define it automatically when webpack is running in development mode).

**Comment by et1975** [comment]
@toburger can you give this plugin a spin, see if it helps?
https://github.com/bvic23/babel-plugin-functional-hmr

**Comment by MangelMaxime** [comment]
@et1975 I don't think this will work because of:

> The plugin transforms arrow expressions if:
>
>    it has JSX return

**Comment by et1975** [comment]
Someone gotta try it, I heard it helped people using Elmish (on RN project).

**Comment by toburger** [comment]
I've tested the plugin with the following configuration but it didn't make any difference:

![](https://i.imgur.com/evx1UOe.png)

**Comment by toburger** [comment]
I came up with the following solution that works quite well for me:

* define a `HMR` constant
```javascript
define: isProduction ? [] : ["DEBUG", "HMR"]
```

* shadow the existing lazy functions
```fsharp
let lazyView x =
    #if HMR
    x
    #else
    Elmish.React.Common.lazyView x
    #endif

let lazyViewWith cmp x =
    #if HMR
    x
    #else
    Elmish.React.Common.lazyViewWith cmp x
    #endif

let lazyView2 x =
    #if HMR
    x
    #else
    Elmish.React.Common.lazyView2 x
    #endif

let lazyView2With cmp x =
    #if HMR
    x
    #else
    Elmish.React.Common.lazyView2With cmp x
    #endif

let lazyView3 x =
    #if HMR
    x
    #else
    Elmish.React.Common.lazyView3 x
    #endif

let lazyView3With cmp x =
    #if HMR
    x
    #else
    Elmish.React.Common.lazyView3With cmp x
    #endif
```

* conditionally include `Program.withHMR`
```fsharp
#if HMR
|> Program.withHMR
#endif
```

**Comment by et1975** [comment]
A couple of thoughts:
- whatever the solution, if any, it better go into Elmish.HMR, not into this repo.
- it seems @MangelMaxime is already on the right track - HMR impl needs to thread the view version into the equality check.

I imagine following implementation:
- function to aggregate HMR state into the `'model`
- equality function that breaks out HMR state from the `'model` for version comparison and forwards the rest to the user's equality function
- a view function that breaks out and discards the HMR state and forwards the rest to the user's view function
- Auto-opening HMR.Common module shadowing the `lazy` functions from React lib with the implementations that augment `view`, `state` and `equal` with the above functions

**Comment by MangelMaxime** [comment]
I believe the easiest way is to use the `HMR.Common` shadowing.

Module code would be something like:

```fs
module HMR.Common

let inline lazyView x = x

let inline lazyViewWith cmp x = x

// Etc.
```

User code:

```fs
#if HMR
open HMR.Common
#endif
```

And also adding the `HMR`constant to webpack config.

**Comment by et1975** [comment]
Closing it here, we can continue in HMR repo if needed.
