### ISSUE TITLE
Can we increase Fable.React version?

### ISSUE THREAD

**Issue by semuserable** [fable-elmish/react#45]
## Request

If you install `Fable.Elmish.React` it includes `Fable.React` of version `5.1.0`. Can it be increased to the most recent (stable) one - `5.3.5` (as of now)?

## Problem

Spent some time trying to figure out why some API wasn't available (but it is in `Fable.React` repo). Turns out I was relying on `Fable.Elmish.React` references (which uses `Fable.React` of version `5.1.0`). But I needed to use the latest one, so I installed the latest `Fable.React` separately.

**Comment by MangelMaxime** [comment]
In general, this is normal to keep the dependencies version lower because people can always use a newer one. While if we set it too high, people have no way to restrict their version and can be forced to migrate their code.

I think you problem, is more that Fable.React doesn't make a good job at explaining what API is available since which version.

But if @et1975, accept to upgrade the deps, I have no opposition to it personnaly.

**Comment by et1975** [comment]
Like Maxime said this is normal and the way you solved it is exactly how it
is supposed to be done in nuget ecosystem.

**Comment by semuserable** [comment]
Understood, closing it.
